# Generated by Django 5.2.6 on 2026-05-24 22:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("empresas", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("name", models.CharField(max_length=255)),
                ("nif", models.CharField(max_length=32)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, max_length=64)),
                ("address", models.CharField(max_length=255)),
                ("city", models.CharField(default="Luanda", max_length=120)),
                ("country", models.CharField(default="Angola", max_length=120)),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_set",
                        to="empresas.empresa",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "indexes": [
                    models.Index(
                        fields=["empresa", "nif"], name="clientes_cl_empresa_aa1918_idx"
                    ),
                    models.Index(
                        fields=["empresa", "name"],
                        name="clientes_cl_empresa_7cf2a2_idx",
                    ),
                ],
                "unique_together": {("empresa", "nif")},
            },
        ),
    ]
