# Generated by Django 5.2.6 on 2026-05-24 22:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("empresas", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("code", models.CharField(max_length=64)),
                ("name", models.CharField(max_length=255)),
                ("category", models.CharField(max_length=120)),
                ("price", models.DecimalField(decimal_places=2, max_digits=18)),
                (
                    "stock",
                    models.DecimalField(decimal_places=3, default=0, max_digits=18),
                ),
                (
                    "tax_rate",
                    models.DecimalField(decimal_places=2, default=14, max_digits=5),
                ),
                ("exemption_code", models.CharField(blank=True, max_length=32)),
                ("unit", models.CharField(default="UN", max_length=16)),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_set",
                        to="empresas.empresa",
                    ),
                ),
            ],
            options={
                "ordering": ["code"],
                "indexes": [
                    models.Index(
                        fields=["empresa", "code"],
                        name="produtos_pr_empresa_eaab76_idx",
                    ),
                    models.Index(
                        fields=["empresa", "category"],
                        name="produtos_pr_empresa_16227e_idx",
                    ),
                ],
                "unique_together": {("empresa", "code")},
            },
        ),
    ]
