# Generated by Django 5.2.6 on 2026-06-06 21:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empresas", "0001_initial"),
        ("produtos", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StockMovement",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                (
                    "type",
                    models.CharField(
                        choices=[("In", "Entrada"), ("Out", "Saída")], max_length=3
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=3, max_digits=18)),
                ("reason", models.CharField(max_length=255)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.AddField(
            model_name="product",
            name="cost_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name="product",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="product",
            name="min_stock",
            field=models.DecimalField(decimal_places=3, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name="product",
            name="type",
            field=models.CharField(
                choices=[("P", "Produto"), ("S", "Serviço")], default="P", max_length=1
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["empresa", "is_active"], name="produtos_pr_empresa_97a744_idx"
            ),
        ),
        migrations.AddField(
            model_name="stockmovement",
            name="empresa",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(app_label)s_%(class)s_set",
                to="empresas.empresa",
            ),
        ),
        migrations.AddField(
            model_name="stockmovement",
            name="operator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="stockmovement",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="movements",
                to="produtos.product",
            ),
        ),
        migrations.AddIndex(
            model_name="stockmovement",
            index=models.Index(
                fields=["empresa", "product", "timestamp"],
                name="produtos_st_empresa_f6f1e8_idx",
            ),
        ),
    ]
