# Generated by Django 5.2.6 on 2026-06-17 21:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("empresas", "0007_empresa_software_public_key"),
    ]

    operations = [
        migrations.CreateModel(
            name="FiscalCertificate",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "certificate_file",
                    models.FileField(blank=True, null=True, upload_to="certificates/"),
                ),
                ("certificate_password", models.CharField(blank=True, max_length=512)),
                ("serial_number", models.CharField(blank=True, max_length=100)),
                ("issued_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=False)),
                ("software_private_key", models.TextField(blank=True)),
                ("software_public_key", models.TextField(blank=True)),
                (
                    "agt_private_key",
                    models.TextField(
                        blank=True,
                        help_text="Chave privada do contribuinte fornecida pela AGT",
                    ),
                ),
                (
                    "empresa",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fiscal_certificate",
                        to="empresas.empresa",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="FiscalEvent",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("entity_type", models.CharField(max_length=50)),
                ("entity_id", models.UUIDField()),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("DOCUMENT_CREATED", "Documento criado"),
                            ("DOCUMENT_SIGNED", "Assinado JWS"),
                            ("DOCUMENT_SENT", "Enviado AGT"),
                            ("DOCUMENT_ACCEPTED", "Aceite AGT"),
                            ("DOCUMENT_REJECTED", "Rejeitado AGT"),
                            ("DOCUMENT_CANCELLED", "Cancelado"),
                            ("CERTIFICATE_UPDATED", "Certificado actualizado"),
                        ],
                        max_length=30,
                    ),
                ),
                ("payload", models.JSONField(default=dict)),
                ("agt_request_id", models.CharField(blank=True, max_length=100)),
                ("agt_response", models.JSONField(default=dict)),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fiscal_events",
                        to="empresas.empresa",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DocumentSeries",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("document_type", models.CharField(max_length=5)),
                ("series_code", models.CharField(max_length=50)),
                ("agt_registration_id", models.CharField(blank=True, max_length=100)),
                ("current_number", models.PositiveIntegerField(default=1)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_series",
                        to="empresas.empresa",
                    ),
                ),
                (
                    "estabelecimento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_series",
                        to="empresas.estabelecimento",
                    ),
                ),
            ],
            options={
                "unique_together": {
                    ("empresa", "estabelecimento", "document_type", "series_code")
                },
            },
        ),
    ]
