# Generated by Django 5.2.6 on 2026-06-18 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empresas", "0007_empresa_software_public_key"),
        ("fiscal", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="fiscalcertificate",
            options={"verbose_name": "Certificado Fiscal"},
        ),
        migrations.AlterModelOptions(
            name="fiscalevent",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterUniqueTogether(
            name="documentseries",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="documentseries",
            name="fiscal_year",
            field=models.PositiveIntegerField(default=2026),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="documentseries",
            name="is_deleted",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="documentseries",
            name="status",
            field=models.CharField(
                choices=[
                    ("Draft", "Rascunho"),
                    ("Requested", "Solicitada"),
                    ("Approved", "Aprovada"),
                    ("Rejected", "Rejeitada"),
                    ("Inactive", "Inativa"),
                ],
                default="Draft",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="fiscalcertificate",
            name="is_deleted",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="fiscalevent",
            name="is_deleted",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="documentseries",
            name="current_number",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="documentseries",
            name="document_type",
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name="documentseries",
            name="empresa",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(app_label)s_%(class)s_set",
                to="empresas.empresa",
            ),
        ),
        migrations.AlterField(
            model_name="documentseries",
            name="series_code",
            field=models.CharField(max_length=24),
        ),
        migrations.AlterField(
            model_name="fiscalcertificate",
            name="empresa",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(app_label)s_%(class)s_set",
                to="empresas.empresa",
            ),
        ),
        migrations.AlterField(
            model_name="fiscalevent",
            name="empresa",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(app_label)s_%(class)s_set",
                to="empresas.empresa",
            ),
        ),
        migrations.AlterField(
            model_name="fiscalevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("DOCUMENT_CREATED", "Documento criado"),
                    ("DOCUMENT_SIGNED", "Assinado JWS"),
                    ("DOCUMENT_SENT", "Enviado AGT"),
                    ("DOCUMENT_ACCEPTED", "Aceite AGT"),
                    ("DOCUMENT_REJECTED", "Rejeitado AGT"),
                    ("DOCUMENT_CANCELLED", "Cancelado"),
                    ("CERTIFICATE_UPDATED", "Certificado actualizado"),
                    ("ACTIVATION_STARTED", "Ativação iniciada"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="documentseries",
            unique_together={
                (
                    "empresa",
                    "estabelecimento",
                    "series_code",
                    "document_type",
                    "fiscal_year",
                )
            },
        ),
        migrations.AlterUniqueTogether(
            name="fiscalcertificate",
            unique_together={("empresa",)},
        ),
        migrations.AddIndex(
            model_name="documentseries",
            index=models.Index(
                fields=["empresa", "estabelecimento", "document_type", "is_active"],
                name="fiscal_docu_empresa_518845_idx",
            ),
        ),
    ]
