# Generated by Django 5.2.6 on 2026-05-24 22:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Empresa",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("name", models.CharField(max_length=255)),
                ("nif", models.CharField(max_length=32, unique=True)),
                ("address", models.CharField(max_length=255)),
                ("city", models.CharField(default="Luanda", max_length=120)),
                ("country", models.CharField(default="Angola", max_length=120)),
                ("fiscal_regime", models.CharField(max_length=255)),
                ("logo_url", models.URLField(blank=True)),
                ("agt_certificate_no", models.CharField(blank=True, max_length=64)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["nif"], name="empresas_em_nif_887898_idx"),
                    models.Index(
                        fields=["is_active", "is_deleted"],
                        name="empresas_em_is_acti_682fb4_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="EmpresaMembership",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("owner", "Proprietário"),
                            ("admin", "Administrador"),
                            ("member", "Membro"),
                            ("auditor", "Auditor"),
                        ],
                        default="member",
                        max_length=32,
                    ),
                ),
                ("is_default", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="empresas.empresa",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="empresa_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user", "is_active"],
                        name="empresas_em_user_id_01f6be_idx",
                    ),
                    models.Index(
                        fields=["empresa", "is_active"],
                        name="empresas_em_empresa_0704cb_idx",
                    ),
                ],
                "unique_together": {("user", "empresa")},
            },
        ),
    ]
