# Generated by Django 5.2.6 on 2026-06-06 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empresas", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="empresa",
            name="agt_private_key",
            field=models.TextField(
                blank=True, help_text="Chave privada do contribuinte fornecida pela AGT"
            ),
        ),
        migrations.AddField(
            model_name="empresa",
            name="software_private_key",
            field=models.TextField(
                blank=True,
                help_text="Chave privada do produtor (usada para jwsSoftwareSignature)",
            ),
        ),
    ]
