# Generated by Django 5.2.6 on 2026-06-06 22:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empresas", "0002_empresa_agt_private_key_empresa_software_private_key"),
    ]

    operations = [
        migrations.CreateModel(
            name="Estabelecimento",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                (
                    "code",
                    models.CharField(
                        help_text="Código oficial da AGT (ex: SEDE, LOJA01)",
                        max_length=32,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("address", models.CharField(max_length=255)),
                ("city", models.CharField(default="Luanda", max_length=120)),
                ("phone", models.CharField(blank=True, max_length=32)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_set",
                        to="empresas.empresa",
                    ),
                ),
            ],
            options={
                "ordering": ["code"],
                "indexes": [
                    models.Index(
                        fields=["empresa", "code"],
                        name="empresas_es_empresa_de454c_idx",
                    )
                ],
                "unique_together": {("empresa", "code")},
            },
        ),
    ]
