# Generated by Django 5.2.6 on 2026-06-11 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empresas", "0003_estabelecimento"),
    ]

    operations = [
        migrations.AddField(
            model_name="empresa",
            name="primary_color",
            field=models.CharField(default="#3b82f6", max_length=7),
        ),
        migrations.AddField(
            model_name="empresa",
            name="system_name",
            field=models.CharField(default="FACTURYAN ERP", max_length=100),
        ),
    ]
