# Generated by Django 5.2.6 on 2026-06-11 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empresas", "0004_empresa_primary_color_empresa_system_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="estabelecimento",
            name="address",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="estabelecimento",
            name="city",
            field=models.CharField(blank=True, default="Luanda", max_length=120),
        ),
    ]
