# Generated by Django 5.2.6 on 2026-06-11 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empresas", "0005_alter_estabelecimento_address_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="empresa",
            name="address",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="empresa",
            name="city",
            field=models.CharField(blank=True, default="Luanda", max_length=120),
        ),
        migrations.AlterField(
            model_name="empresa",
            name="country",
            field=models.CharField(blank=True, default="Angola", max_length=120),
        ),
        migrations.AlterField(
            model_name="empresa",
            name="fiscal_regime",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="empresa",
            name="nif",
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name="empresa",
            name="primary_color",
            field=models.CharField(blank=True, default="#3b82f6", max_length=7),
        ),
        migrations.AlterField(
            model_name="empresa",
            name="system_name",
            field=models.CharField(blank=True, default="FACTURYAN ERP", max_length=100),
        ),
    ]
