# Generated by Django 5.2.6 on 2026-06-13 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empresas", "0006_alter_empresa_address_alter_empresa_city_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="empresa",
            name="software_public_key",
            field=models.TextField(blank=True, help_text="Chave pública do produtor"),
        ),
    ]
