# Generated by Django 5.2.6 on 2026-05-31 12:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clientes", "0001_initial"),
        ("empresas", "0001_initial"),
        ("facturacao", "0005_invoice_paid_amount"),
    ]

    operations = [
        migrations.CreateModel(
            name="Recibo",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("receipt_no", models.CharField(blank=True, max_length=32)),
                ("issue_date", models.DateField(blank=True, null=True)),
                (
                    "total_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("CH", "Numerário"),
                            ("TR", "Transferência Bancária"),
                            ("TP", "TPA"),
                            ("DP", "Depósito"),
                            ("OU", "Outro"),
                        ],
                        default="CH",
                        max_length=2,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Draft", "Rascunho"),
                            ("Issued", "Emitido"),
                            ("Cancelled", "Cancelado"),
                        ],
                        default="Draft",
                        max_length=12,
                    ),
                ),
                ("previous_hash", models.CharField(blank=True, max_length=255)),
                ("receipt_hash", models.CharField(blank=True, max_length=255)),
                ("qrcode_string", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recibos",
                        to="clientes.client",
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_set",
                        to="empresas.empresa",
                    ),
                ),
            ],
            options={
                "ordering": ["-issue_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReciboItem",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("amount_paid", models.DecimalField(decimal_places=2, max_digits=18)),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_set",
                        to="empresas.empresa",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="receipt_items",
                        to="facturacao.invoice",
                    ),
                ),
                (
                    "recibo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="pagamentos.recibo",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddIndex(
            model_name="recibo",
            index=models.Index(
                fields=["empresa", "receipt_no"], name="pagamentos__empresa_0cfb67_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="recibo",
            index=models.Index(
                fields=["empresa", "issue_date"], name="pagamentos__empresa_8c6a3b_idx"
            ),
        ),
    ]
