# Generated by Django 5.2.6 on 2026-06-04 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clientes", "0001_initial"),
        ("empresas", "0001_initial"),
        ("pagamentos", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="recibo",
            index=models.Index(
                fields=["empresa", "client_id"], name="pagamentos__empresa_878b82_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="recibo",
            index=models.Index(
                fields=["client_id", "issue_date"], name="idx_recibo_client_date"
            ),
        ),
    ]
