# Generated by Django 5.2.6 on 2026-06-11 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pagamentos", "0002_recibo_pagamentos__empresa_878b82_idx_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="recibo",
            name="pagamentos__empresa_878b82_idx",
        ),
    ]
