# Generated by Django 5.2.6 on 2026-06-14 21:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empresas", "0007_empresa_software_public_key"),
        ("facturacao", "0013_invoice_delivery_date_invoice_delivery_point_and_more"),
        ("pagamentos", "0003_remove_recibo_pagamentos__empresa_878b82_idx"),
    ]

    operations = [
        migrations.CreateModel(
            name="MulticaixaReference",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                (
                    "entity_code",
                    models.CharField(
                        help_text="Código da Entidade (ex: 00245)", max_length=5
                    ),
                ),
                ("reference_number", models.CharField(max_length=9, unique=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=18)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pendente"),
                            ("PAID", "Pago"),
                            ("EXPIRED", "Expirado"),
                            ("CANCELLED", "Cancelado"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                (
                    "provider_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_set",
                        to="empresas.empresa",
                    ),
                ),
                (
                    "invoice",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="multicaixa_reference",
                        to="facturacao.invoice",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
