# Generated by Django 5.2.6 on 2026-06-17 19:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("empresas", "0007_empresa_software_public_key"),
    ]

    operations = [
        migrations.CreateModel(
            name="SupplierInvoice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                (
                    "supplier_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "supplier_nif",
                    models.CharField(blank=True, max_length=32, null=True),
                ),
                ("invoice_no", models.CharField(blank=True, max_length=100, null=True)),
                ("issue_date", models.DateField(blank=True, null=True)),
                (
                    "subtotal",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "tax_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "grand_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                ("currency", models.CharField(default="AOA", max_length=3)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pendente de Revisão"),
                            ("VALIDATED", "Confirmada"),
                            ("PAID", "Paga"),
                            ("CANCELLED", "Anulada"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True, null=True, upload_to="supplier_invoices/%Y/%m/"
                    ),
                ),
                (
                    "raw_ai_analysis",
                    models.JSONField(
                        blank=True, help_text="Resposta bruta da IA", null=True
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_set",
                        to="empresas.empresa",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SupplierInvoiceItem",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("description", models.CharField(max_length=500)),
                ("quantity", models.DecimalField(decimal_places=3, max_digits=18)),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=18)),
                (
                    "tax_rate",
                    models.DecimalField(decimal_places=2, default=14, max_digits=5),
                ),
                ("total", models.DecimalField(decimal_places=2, max_digits=18)),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_set",
                        to="empresas.empresa",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="compras.supplierinvoice",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
