# Generated by Django 5.2.6 on 2026-05-30 23:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("empresas", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SaftExportJob",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("year", models.PositiveIntegerField()),
                ("month", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pendente"),
                            ("Ready", "Pronto"),
                            ("Error", "Erro"),
                        ],
                        default="Pending",
                        max_length=16,
                    ),
                ),
                ("filename", models.CharField(max_length=255)),
                ("file", models.FileField(blank=True, upload_to="saft/exports/")),
                ("error_message", models.TextField(blank=True)),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_set",
                        to="empresas.empresa",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="saft_export_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["empresa", "status", "created_at"],
                        name="saft_saftex_empresa_c58e56_idx",
                    ),
                    models.Index(
                        fields=["empresa", "year", "month"],
                        name="saft_saftex_empresa_6602f4_idx",
                    ),
                ],
            },
        ),
    ]
