# Generated by Django 5.2.6 on 2026-05-24 22:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clientes", "0001_initial"),
        ("empresas", "0001_initial"),
        ("produtos", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Invoice",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("invoice_no", models.CharField(blank=True, max_length=64)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("FT", "Factura"),
                            ("FR", "Factura-Recibo"),
                            ("VD", "Venda a Dinheiro"),
                            ("NC", "Nota de Crédito"),
                        ],
                        max_length=8,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Draft", "Rascunho"),
                            ("Issued", "Emitida"),
                            ("Paid", "Paga"),
                            ("Partial", "Parcial"),
                            ("Cancelled", "Cancelada"),
                            ("AGT_Synced", "Sincronizada AGT"),
                            ("AGT_Error", "Erro AGT"),
                        ],
                        default="Draft",
                        max_length=24,
                    ),
                ),
                ("issue_date", models.DateField(blank=True, null=True)),
                ("due_date", models.DateField(blank=True, null=True)),
                ("client_name", models.CharField(max_length=255)),
                ("client_nif", models.CharField(max_length=32)),
                ("client_address", models.CharField(max_length=255)),
                (
                    "subtotal",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "discount_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "tax_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "withholding_tax_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "withholding_tax_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "grand_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                ("invoice_hash", models.CharField(blank=True, max_length=128)),
                ("previous_hash", models.CharField(blank=True, max_length=128)),
                ("qrcode_string", models.TextField(blank=True)),
                ("agt_sync_date", models.DateTimeField(blank=True, null=True)),
                ("agt_response_code", models.CharField(blank=True, max_length=128)),
                ("notes", models.TextField(blank=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invoices",
                        to="clientes.client",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_invoices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_set",
                        to="empresas.empresa",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InvoiceItem",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("product_name", models.CharField(max_length=255)),
                ("quantity", models.DecimalField(decimal_places=3, max_digits=18)),
                ("price", models.DecimalField(decimal_places=2, max_digits=18)),
                ("tax_rate", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "discount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "total_tax",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "subtotal",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_set",
                        to="empresas.empresa",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="facturacao.invoice",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="produtos.product",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FiscalSeries",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("code", models.CharField(max_length=24)),
                ("document_type", models.CharField(max_length=8)),
                ("fiscal_year", models.PositiveIntegerField()),
                ("current_number", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_set",
                        to="empresas.empresa",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["empresa", "document_type", "fiscal_year", "is_active"],
                        name="facturacao__empresa_316e97_idx",
                    )
                ],
                "unique_together": {
                    ("empresa", "code", "document_type", "fiscal_year")
                },
            },
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["empresa", "status"], name="facturacao__empresa_3d747a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["empresa", "issue_date"], name="facturacao__empresa_cfda8b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["empresa", "invoice_no"], name="facturacao__empresa_43b454_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="invoice",
            unique_together={("empresa", "invoice_no")},
        ),
        migrations.AddIndex(
            model_name="invoiceitem",
            index=models.Index(
                fields=["empresa", "invoice"], name="facturacao__empresa_b70cd8_idx"
            ),
        ),
    ]
