# Generated by Django 5.2.6 on 2026-05-30 22:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empresas", "0001_initial"),
        ("facturacao", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgtSyncLog",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pendente"),
                            ("Success", "Sucesso"),
                            ("Error", "Erro"),
                        ],
                        default="Pending",
                        max_length=16,
                    ),
                ),
                ("request_payload", models.JSONField(blank=True, default=dict)),
                ("response_payload", models.JSONField(blank=True, default=dict)),
                ("response_code", models.CharField(blank=True, max_length=128)),
                ("error_message", models.TextField(blank=True)),
                ("attempt_count", models.PositiveIntegerField(default=1)),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_set",
                        to="empresas.empresa",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="agt_sync_logs",
                        to="facturacao.invoice",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["empresa", "invoice", "status"],
                        name="facturacao__empresa_d3e7c1_idx",
                    ),
                    models.Index(
                        fields=["empresa", "status", "created_at"],
                        name="facturacao__empresa_553b0e_idx",
                    ),
                ],
            },
        ),
    ]
