# Generated by Django 5.2.6 on 2026-05-30 23:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empresas", "0001_initial"),
        ("facturacao", "0003_invoice_cancellation"),
    ]

    operations = [
        migrations.CreateModel(
            name="InvoiceDocument",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pendente"),
                            ("Ready", "Pronto"),
                            ("Error", "Erro"),
                        ],
                        default="Pending",
                        max_length=16,
                    ),
                ),
                ("file", models.FileField(blank=True, upload_to="invoices/pdf/")),
                ("error_message", models.TextField(blank=True)),
                ("generated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_set",
                        to="empresas.empresa",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="facturacao.invoice",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["empresa", "invoice", "status"],
                        name="facturacao__empresa_0f9d04_idx",
                    )
                ],
            },
        ),
    ]
