# Generated by Django 5.2.6 on 2026-05-31 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facturacao", "0004_invoicedocument"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="paid_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
    ]
