# Generated by Django 5.2.6 on 2026-06-03 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("facturacao", "0005_invoice_paid_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="origin_document",
            field=models.ForeignKey(
                blank=True,
                help_text="Factura original em caso de Nota de Crédito",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="credit_notes",
                to="facturacao.invoice",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="rectification_reason",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
