# Generated by Django 5.2.6 on 2026-06-04 20:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clientes", "0001_initial"),
        ("empresas", "0001_initial"),
        ("facturacao", "0006_invoice_origin_document"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["empresa", "due_date"], name="facturacao__empresa_2129cd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["empresa", "type", "issue_date"], name="idx_empresa_type_date"
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["client_id", "issue_date"], name="idx_client_date"
            ),
        ),
    ]
