# Generated by Django 5.2.6 on 2026-06-06 22:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empresas", "0003_estabelecimento"),
        ("facturacao", "0007_invoice_facturacao__empresa_2129cd_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExchangeRate",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                (
                    "currency_code",
                    models.CharField(help_text="Ex: USD, EUR", max_length=3),
                ),
                (
                    "rate",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Taxa para 1 unidade da moeda estrangeira em AOA",
                        max_digits=18,
                    ),
                ),
                ("date", models.DateField()),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
        migrations.RemoveIndex(
            model_name="fiscalseries",
            name="facturacao__empresa_316e97_idx",
        ),
        migrations.AlterUniqueTogether(
            name="fiscalseries",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="fiscalseries",
            name="estabelecimento",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="series",
                to="empresas.estabelecimento",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="currency",
            field=models.CharField(default="AOA", max_length=3),
        ),
        migrations.AddField(
            model_name="invoice",
            name="estabelecimento",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="invoices",
                to="empresas.estabelecimento",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="exchange_rate",
            field=models.DecimalField(decimal_places=4, default=1, max_digits=18),
        ),
        migrations.AlterUniqueTogether(
            name="fiscalseries",
            unique_together={
                ("empresa", "estabelecimento", "code", "document_type", "fiscal_year")
            },
        ),
        migrations.AddIndex(
            model_name="fiscalseries",
            index=models.Index(
                fields=["empresa", "estabelecimento", "document_type", "is_active"],
                name="facturacao__empresa_157f23_idx",
            ),
        ),
        migrations.AddField(
            model_name="exchangerate",
            name="empresa",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(app_label)s_%(class)s_set",
                to="empresas.empresa",
            ),
        ),
        migrations.AddIndex(
            model_name="exchangerate",
            index=models.Index(
                fields=["empresa", "currency_code", "date"],
                name="facturacao__empresa_809798_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="exchangerate",
            unique_together={("empresa", "currency_code", "date")},
        ),
    ]
