# Generated by Django 5.2.6 on 2026-06-06 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empresas", "0003_estabelecimento"),
        ("facturacao", "0008_exchangerate_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="agtsynclog",
            name="request_id",
            field=models.CharField(
                blank=True,
                help_text="ID retornado pela AGT para consulta de estado",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="agtsynclog",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pendente"),
                    ("Waiting", "Aguardar Validação"),
                    ("Success", "Sucesso"),
                    ("Error", "Erro"),
                ],
                default="Pending",
                max_length=16,
            ),
        ),
        migrations.AddIndex(
            model_name="agtsynclog",
            index=models.Index(
                fields=["request_id"], name="facturacao__request_5b3696_idx"
            ),
        ),
    ]
