# Generated by Django 5.2.6 on 2026-06-14 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facturacao", "0009_agtsynclog_request_id_alter_agtsynclog_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="type",
            field=models.CharField(
                choices=[
                    ("FT", "Factura"),
                    ("FR", "Factura-Recibo"),
                    ("VD", "Venda a Dinheiro"),
                    ("NC", "Nota de Crédito"),
                    ("PP", "Factura Proforma"),
                ],
                max_length=8,
            ),
        ),
    ]
