# Generated by Django 5.2.6 on 2026-06-14 16:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facturacao", "0011_recurringinvoice_recurringinvoiceitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="public_token",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="type",
            field=models.CharField(
                choices=[
                    ("FT", "Factura"),
                    ("FR", "Factura-Recibo"),
                    ("VD", "Venda a Dinheiro"),
                    ("NC", "Nota de Crédito"),
                    ("PP", "Factura Proforma"),
                    ("ND", "Nota de Débito"),
                ],
                max_length=8,
            ),
        ),
    ]
