# Generated by Django 5.2.6 on 2026-06-14 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facturacao", "0012_invoice_public_token_alter_invoice_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="delivery_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="invoice",
            name="delivery_point",
            field=models.TextField(
                blank=True, help_text="Local de descarga", null=True
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="driver_name",
            field=models.CharField(
                blank=True, help_text="Nome do motorista", max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="loading_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="invoice",
            name="loading_point",
            field=models.TextField(blank=True, help_text="Local de carga", null=True),
        ),
        migrations.AddField(
            model_name="invoice",
            name="vehicle_plate",
            field=models.CharField(
                blank=True, help_text="Matricula do veiculo", max_length=32, null=True
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="type",
            field=models.CharField(
                choices=[
                    ("FT", "Factura"),
                    ("FR", "Factura-Recibo"),
                    ("VD", "Venda a Dinheiro"),
                    ("NC", "Nota de Crédito"),
                    ("PP", "Factura Proforma"),
                    ("ND", "Nota de Débito"),
                    ("GR", "Guia de Remessa"),
                ],
                max_length=8,
            ),
        ),
    ]
